### PR TITLE
Fix: Observing a collection duplicates values

### LINKED ISSUE #180: Listening to List is duplicating values
I have an Object with a list of integers. I want to listen to the list so I can see when a value is added. The Updates come in at the right time, but every time the list receives an update, it has duplicated all of the values.

(Initial setup, list exists and has 10 values)
1. Start listening to the list
2. Add a value, I receive an updated list with 11 values
3. Add another value, I receive an updated list with 23 values, the 12 were appended instead of just the 1

Example Code:
```
public class ParentObject {
  public List<int> Values {get; set;} = new List<int>();
}

public async void ListenAndUpdate() {
    // Assume a valid ParentObject exists with this key at collection 'parentobjects'
    var testId = "testkey";

    var parentObject = await GetSingle(testId);

    // start listening for changes to "testkey"
    ListenForChangesToValues(testId);

    for(int i = 0; i < 10; i++)
    {
        parentObject.Values.Add(1);
        await Update(testId, parentObject);
        Thread.Sleep(5000);
    }
}


public void ListenForChangesToValues(string id){
    firebaseClient
        .Child("parentobjects")
        .Child(id)
        .Child(nameof(ParentObject.Values))
        .AsObservable<List<int>>(elementRoot: nameof(ParentObject.Values))
        // The first time this comes back, the length is correct, subsequent times it has duplicated values
        .Subscribe(newValues => Console.WriteLine(newValues.Object.Count));
}

public async Task Update(string id, ParentObject item) {
    await firebaseClient
        .Child("parentobjects")
        .Child(id)
        .PutAsync<ParentObject>(item);
}

public async Task<ParentObject> GetSingle(string id){
    var model = await firebaseClient
        .Child("parentobjects")
        .Child(id)
        .OnceSingleAsync<ParentObject>();
    return model;
}
```
It is worth noting that the values are not being duplicated in firebase, only the returned values passed into the Subscribe Action. Seems like a bug, but possible I'm just misusing the library.

Thanks for your time! Overall a huge fan of this project.

### PR DESCRIPTION
**Pull request by cabauman**
- More specifically, the updated collection gets appended to the original instead of replacing it.

Closes #180

### CODE REVIEW

File: src/Firebase/Streaming/FirebaseCache.cs [hunk 1]
```diff
@@ -153,7 +152,6 @@ public IEnumerable<FirebaseObject<T>> PushData(string path, string data, bool re
                     JsonConvert.PopulateObject(data, obj, this.serializerSettings);
                 }
 
-                this.dictionary[pathElements[0]] = this.dictionary[pathElements[0]];
```
Comment (bezysoftware) [inline src/Firebase/Streaming/FirebaseCache.cs]: This is need to make offline storage work, the dictionary can be an OfflineDatabase and assigning value to "self" triggers an upsert - https://github.com/step-up-labs/firebase-database-dotnet/blob/master/src/Firebase/Offline/OfflineDatabase.cs#L82

**Comment by bezysoftware** [comment]
Published to nuget, thanks!

**Comment by cabauman** [comment]
No problem!
